### ISSUE TITLE
YouTube API Research

### ISSUE THREAD

**Issue by jar4677** [jar4677/C8_hackathon#6]

**Comment by BetsyGott** [comment]
Youtube API Info:

URL:
s-apis.learningfuze.com/hackathon/youtube/search.php
DATA:
q (string) search term to search youtube for
maxResults: (number) number of results to return in one search
RESPONSE:
video: (object) JS object containing an array of video objects, which have the properties:
- title (string): title of video
- "id" (string): ID of video

The ID will go into the "src" attr of an iframe element on the page. Here is an example iframe element:

```
<iframe id="ytplayer" type="text/html" width="640" height="390"
  src="http://www.youtube.com/embed/M7lc1UVf-VE?autoplay=1&origin=http://example.com"
  frameborder="0"/>
```
- width/height should definitely be set! I think 640 x 390 is the default youtube video size.
- the ID of this video is "M7lc1UVf-VE"
- autoplay is set to 1 which means true, it will autoplay when loaded
- frameborder=0 means no styled border around the iframe element'
- origin: still works without this parameter, adds some extra security, but since we don't have a domain we should prob omit this (as well as the '&' prepending it)
